version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf 
  spring-backend:
    container_name: spring-backend
    build: ./backend
    image: hollyshanks/spring-backend
  spring-backend:
    container_name: react-frontend
    build: ./frontend
    image: hollyshanks/react-frontend