version: "3.8"
services:
  spring-backend:
    container_name: spring-backend
    build: ./
    image: hollyshanks/spring-backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  spring-frontend:
    container_name: spring-frontend
    build: ../frontend/
    image: hollyshanks/spring-front
    ports:
    - target: 5002
      published: 5002
      protocol: tcp