pipeline{
        agent any
        tools {
		    maven 'M3'
		  }
        stages{
            stage('Build'){
                steps{
                	sh '''
                        cd FinalProjectCitizenRepo
                        docker-compose build --parallel
                    '''
                }
            }
            stage('Deploy') { 
                steps {
                    sh '''
                    	cd FinalProjectCitizenRepo
                    	docker-compose up -d
                    '''
                }
           }
        }
}